def crie_linhas():
    print('_________________________________________________________________')
crie_linhas()
print('sistema de alunos')
crie_linhas()
print('cadastro de funcionarios')
crie_linhas()
print('erro do sistema')
crie_linhas()
crie_linhas()
